### ISSUE TITLE
Error near "s" when running sync on Ubuntu 16.04 x64

### ISSUE THREAD

**Issue by rylincoln** [fulcrumapp/fulcrum-desktop#1]
This error pops up during sync at different stages of the sync during successive attempts.  OS = ubuntu 16.04 x64

0.0s 0.1Error: near "s": syntax error
    at Database.get lastError [as lastError] (/home/ry/fulcrum-desktop/node_modules/minisqlite/src/index.js:71:24)
    at statement.getResults.results (/home/ry/fulcrum-desktop/node_modules/minisqlite/src/cursor.js:127:21)
    at Immediate.Statement.setImmediate (/home/ry/fulcrum-desktop/node_modules/minisqlite/src/index.js:147:7)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

Version v0.0.31

Let me know if you need further testing done.

**Comment by zhm** [comment]
Do you have something in your account with an apostrophe "s" at the end of the name? Like an app name? Also, can you tell which state of the sync it's at?

**Comment by rylincoln** [comment]
Yes that's exactly it - there are app names with apostrophe "s" in them.  It first happened when syncing the forms table - i restrated it and it completed syncing the forms table and then errored again on the form with the culprit name in it.  App names maybe should have a little bit of regex restriction set on them.  i.e. no double spaces, no special characters?

**Comment by zhm** [comment]
Fixed over in https://github.com/fulcrumapp/fulcrum-desktop-geopackage/commit/04d7c021cea783585a388778a1d1028f3edf4836

`fulcrum update-plugins` should bring in the fix.
