### ISSUE TITLE
relation does not exist

### ISSUE THREAD

**Issue by rylincoln** [fulcrumapp/fulcrum-desktop#13]
`🤔  Environmental Microbial Sampling Field Data Sheet ▇▇▇▇▇▇▇▇------- 50% (1/2) 0.1s 0.1{ error: relation "account_3_form_702_092b" does not exist
    at Connection.parseE (/home/ubuntu/.fulcrum/plugins/fulcrum-desktop-postgres/node_modules/pg/lib/connection.js:569:11)
    at Connection.parseMessage (/home/ubuntu/.fulcrum/plugins/fulcrum-desktop-postgres/node_modules/pg/lib/connection.js:396:17)
    at Socket.<anonymous> (/home/ubuntu/.fulcrum/plugins/fulcrum-desktop-postgres/node_modules/pg/lib/connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  name: 'error',
  length: 116,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '111',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1160',
  routine: 'parserOpenTable' }`

Above error happens during sync process.

**Comment by rylincoln** [comment]
I just solve these problems by doing a --clean.  Which works for now.
