### ISSUE TITLE
Cannot read property 'find' of undefined during sync

### ISSUE THREAD

**Issue by rylincoln** [fulcrumapp/fulcrum-desktop#17]
running sync to postgresql with forever option - worked for a while then when in another screen session i simultaneously started running the media sync plugin and eventually fulcrum-desktop started dropping this error during each iteration of the sync process(every 10 seconds)
```
TypeError: Cannot read property 'find' of undefined
    at DownloadRoles.getSyncState (/opt/Fulcrum/resources/app.asar/src/main/sync/tasks/task.js:19:12)
    at /opt/Fulcrum/resources/app.asar/src/main/sync/tasks/task.js:29:27
    at Generator.next (<anonymous>)
    at step (/opt/Fulcrum/resources/app.asar/app/main/sync/tasks/task.js:21:191)
    at /opt/Fulcrum/resources/app.asar/app/main/sync/tasks/task.js:21:361
```

I ran a desktop sync with --clean option and got this error once - ran desktop sync again after --clean and it worked fine again(starting all over as expected).  Then I tested running the media plugin again and eventually got the same above error.  I deduce running the two operations at the same time on the same machine creates a conflict?

**Comment by rylincoln** [comment]
Little feeback: 
Seems you can only run these processes in isolation on the same machine. If i run them sequentially it doesn't break things.  I attempted to test running the db sync in the main OS and to setup a chroot environment to run the media sync and got fulcrum-desktop installed in both the native OS and the new chroot env  but it wouldn't run in chroot and I didn't figure out why - that was probably a crazy way to try things anyways....
