### ISSUE TITLE
memberships.role_id

### ISSUE THREAD

**Issue by MrRasmussen** [fulcrumapp/fulcrum-desktop#20]
I am currently working on 3 form with fulcrum the first two forms sync with the fulcrum desktop app perfectly. The third form returns and error:

`2018-07-06T15:27:51.288Z [downloading] memberships
2018-07-06T15:27:51.367Z [processing] memberships
{ Error: NOT NULL constraint failed: memberships.role_id
    at Database.get lastError [as lastError] (C:\Users\user\AppData\Local\Programs\Fulcrum\resources\app.asar\node_modules\minisqlite\dist\index.js:92:24)
    at statement.getResults.results (C:\Users\user\AppData\Local\Programs\Fulcrum\resources\app.asar\node_modules\minisqlite\dist\cursor.js:133:45)
    at Immediate.Statement.setImmediate (C:\Users\user\AppData\Local\Programs\Fulcrum\resources\app.asar\node_modules\minisqlite\dist\index.js:171:7)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) message: 'NOT NULL constraint failed: memberships.role_id' }`

I have the same permissions for all three forms. I'm not sure why it won't grant me access.

**Comment by zhm** [comment]
I think this is a known issue when using Fulcrum Desktop with non-Owner API users. It should work if you use an API token of an Owner of the account.

**Comment by MrRasmussen** [comment]
Is there any other know work around?
I am a manager on all three and working on the backend.

**Comment by MrRasmussen** [comment]
I did `fulcrum setup --token <owner_token>` and ran it again with the same results.

**Comment by zhm** [comment]
Can you try re-installing or clearing the application database and trying again? I think there might be an issue having 2 different tokens setup for the same org. When running sync and only passing an org name, it wouldn't know which token to use.

**Comment by MrRasmussen** [comment]
That work, thanks.

**Comment by zhm** [comment]
Thanks for reporting this issue! We're working to iron out stability issues, so this was helpful. I've made a few changes to improve how this is handled so at least the current limitations are enforced and some error messages are displayed.

**Comment by MrRasmussen** [comment]
Thank you, I appreciate the timely response and your help.
