### ISSUE TITLE
Unable to Setup Geopackage Database with Org on Ubuntu 16.04

### ISSUE THREAD

**Issue by blairdgeo** [fulcrumapp/fulcrum-desktop#22]
Hello,

I am wondering if I am doing something wrong.  I have done the following and am unable to setup a Geopackage database for my organization:

- Ran the install shell script from release page
- Installed the Geopackage plugin
- Updated all packages

When I run the database setup...

```
ubuntu@mysyncmachine:/opt/Fulcrum/scripts$ sudo ./fulcrum geopackage --org 'myorg'

```
I am getting the following error after running for a couple of seconds:

```
Error: near "s": syntax error
    at Database.get lastError [as lastError] (/opt/Fulcrum/resources/app.asar/node_modules/minisqlite/dist/index.js:92:24)
    at statement.getResults.results (/opt/Fulcrum/resources/app.asar/node_modules/minisqlite/dist/cursor.js:133:45)
    at Immediate.Statement.setImmediate (/opt/Fulcrum/resources/app.asar/node_modules/minisqlite/dist/index.js:171:7)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)


```
**Does my database setup syntax look correct?**  Thanks!

Cheers,
Blair

**Comment by blairdgeo** [comment]
This seems to also be happening on my mac fwiw.  Seems like this is either org specific and/or geopackage specific.  Thanks.

**Comment by zhm** [comment]
Thanks for reporting this. I wonder if it’s releated to special SQL characters in an app name. Do you have single quotes in any of your app names?

**Comment by blairdgeo** [comment]
Yes I just notice one.  We have hundreds of forms and a couple with single quotes such as "Aspect's Favorite Trails'.  Are these not supported?  Thanks.

**Comment by zhm** [comment]
It should be supported. This is a bug in this plugin.

**Comment by blairdgeo** [comment]
Thanks @zhm.  This is not happening with the postgres plugin.
