### ISSUE TITLE
Fulcrum 0.0.75 with postgresql plugin not working: error is date type field

### ISSUE THREAD

**Issue by needeco** [fulcrumapp/fulcrum-desktop#24]

**Comment by needeco** [comment]
I am using Postgresql 11 and Fulcrum 0.0.75. Fulcrum desktop is working fine until postgresql plugin not get installed. After installing this plugin i try to run sync command i am gettiong following error:


C:\Users\XXXX\Fulcrum\scripts>fulcrum sync --org     ........
Inititalizing database...
Populating system tables...
Migrating date calculation fields...
Migrating date calculation fields in form... ABCD Project forms
Migrating date calculation fields in form... ABCD_Timesheets
error: invalid input syntax for type date: "1.5"
    at Connection.parseE (C:\Users\XXXX\.fulcrum\plugins\fulcrum-desktop-postgres\node_modules\pg\lib\connection.js:569:11)
    at Connection.parseMessage (C:\Users\XXXX\.fulcrum\plugins\fulcrum-desktop-postgres\node_modules\pg\lib\connection.js:396:17)
    at Socket.<anonymous> (C:\Users\XXXX\.fulcrum\plugins\fulcrum-desktop-postgres\node_modules\pg\lib\connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)

Please let em know if you need any other information to resolve my issue.
Thanks
